### ISSUE TITLE
Signature of Play example does not have correct color in OSX Mail

### ISSUE THREAD

**Issue by yn5** [fadeit/responsive-html-email-signature#19]
The signature of the Play example (the `td` with class `footer__main__signature`) should get color `#f5f5f5` according to it's styling:
```
.footer__main__signature{
  font-size: 14px;
  color: #f5f5f5;
  /* @todo gulp-inline-css doesn't parse align */
  align:left;
}
```

But it doesn't in OSX Mail (but does in Gmail and Outlook 2016):
![screen shot 2016-07-14 at 11 34 48](https://cloud.githubusercontent.com/assets/1705585/16835290/56050a10-49b8-11e6-9d31-5fa4066eb1fd.png)

**Comment by danmindru** [comment]
Did you give the dev branch a try? Wonder if you have the same issue there.
https://github.com/fadeit/responsive-html-email-signature/blob/100%E2%AD%90%EF%B8%8F/dist/dark/signature-dark.html

**Comment by yn5** [comment]
@danmindru Just tried the 100⭐️ branch but unfortunately no luck:
<img width="527" alt="screen shot 2016-07-15 at 01 12 21" src="https://cloud.githubusercontent.com/assets/1705585/16858751/7297e050-4a29-11e6-8daf-11a807bf49d5.png">

**Comment by danmindru** [comment]
That's interesting. Is it El Capitan or an earlier version? I'd like to reproduce it somehow.

It seems like the client default styles are somehow more specific in this case, so I'd wrap the content in a <p> or <span> with `style="color:white;"` (you can use a class and compile it e.g. `.white { color: white; }`)

--
Sent from my phone

**Comment by yn5** [comment]
I'm on Yosemite. But I figured out it was the Gmail web client what caused the problem. There I have (afaik) no other option than copy pasting the footer from a browser window into the Gmail config.

**Comment by danmindru** [comment]
Alright. So did the wrapping fix it? Or could you perhaps change the color after pasting right in the Gmail web client?

**Comment by yn5** [comment]
Didn't try the wrapping yet since it turned out to be a non-issue for me. But the strange thing is it works in all clients I tested except OS X Mail. And thus the color cannot be changed after pasting it into the Gmail web client since it has already the correct color.
