### ISSUE TITLE
gulp process hanging with UnhandledPromiseRejectionWarning error

### ISSUE THREAD

**Issue by alisamii** [fadeit/responsive-html-email-signature#25]
Hi there, please provide some info about your enviornment before submiting this issue:
- device        : Mac
- OS            : macOS Sierra
- email client  : Mail.app
- node version  : v6.9.1
- npm version   : 4.0.1

I am trying to work with your responsive html email signature and I am having some problems.

I have attached to this email two new signatures which I want to test. The zip contains the two directories I have added into the src  directory.

Gulp is returning the following error:

```
$ gulp
[18:58:18] Using gulpfile /Volumes/sites/clients/email-sig/gulpfile.js
[18:58:18] Starting 'build'...
[18:58:18] Starting 'watch'...
[18:58:18] Finished 'watch' after 51 ms
(node:71321) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Invalid or unexpected token
```

It then just appears to hang. I am not sure how to proceed.

Please advise.
[new-src-sigs.zip](https://github.com/fadeit/responsive-html-email-signature/files/552090/new-src-sigs.zip)

**Comment by danmindru** [comment]
Hi, thanks for opening the issue.
Your JSON is invalid: `introParagraph` doesn't have an ending quote `'` in both conf files.

There's a JSON linter on the dev branch (1bdbed78c96651f1ff5bb428582fbf8ab08705e0), but hasn't been merge into master just yet.
