### ISSUE TITLE
Gulp inline css not working

### ISSUE THREAD

**Issue by paulmassen** [fadeit/responsive-html-email-signature#26]
Hi, 

I have an issue with gulp-inline-css and I can't figure what is wrong.
The error is as below
```
[13:30:44] Plumber found unhandled error:
 Error in plugin 'gulp-inline-css'
Message:
    getaddrinfo ENOTFOUND c c:80
Details:
    code: ENOTFOUND
    errno: ENOTFOUND
    syscall: getaddrinfo
    hostname: c
    host: c
    port: 80
    response: undefined
```

I tried to modify tasks/build.js to specify the url of the stylesheets as below:
```
.pipe(inlineCss({
                applyTableAttributes: true,
                applyWidthAttributes: true,
                url: 'file://' + cwd + '*.css',
                preserveMediaQueries: true,
                removeStyleTags: false
              }))
```

But it still doesn't work.

Any idea? Thanks a lot in advance

**Comment by danmindru** [comment]
Hi there, you shouldn't have to modify the build.

What's node version are you running? <br/>
Also, can you run `tree templates` in the root of the project?

**Comment by paulmassen** [comment]
Thanks for your quick answer, here is my tree templates result:

```
C:\USERS\PAUL\DEVELOPPEMENT\SIGNATURE\TEMPLATES
├───dark
│   └───assets
└───light
    └───assets
```
and I'm running node v6.9.4

Let me know if you need some other info!

**Comment by paulmassen** [comment]
Just took a quick look at previous commits and saw src was renamed to templates. Could it be related?

**Comment by danmindru** [comment]
Hey Paul, 

It had something to do with the newer version of node returning inconsistent paths for Windows / Unix. I myself am not a Windows user, so I wasn't aware that upgrading node affected this, sorry for that :)

Pull the code @ https://github.com/fadeit/responsive-html-email-signature/commit/12bffe8169b6ad2986af830291be65c116ee52a5 and give it a go. LMK if there are any other problems, I tested on Win 7/8.

Cheers, Dan

**Comment by paulmassen** [comment]
Thank you for this quick fix, it is working perfectly indeed!

Cheers,

Paul
