### ISSUE TITLE
Gulp Syntax Error: Unexpected Token

### ISSUE THREAD

**Issue by Mulegoat** [fadeit/responsive-html-email-signature#28]
Hi there, please provide some info about your enviornment before submiting this issue:
- device        : NA
- OS            : Windows
- email client  : NA
- node version  : 4.4.0
- npm version   : 3.8.1
- error message : Unexpected token...

at exports.runThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Function.Module.load (module.js:300:12)
at require (internal/module.js:12:17)
at loadTasks (path\to\gulp\file\gulpfile.js:26:5)
at Array.map (native)
at Object.<anonnymous> (path\to\gulp\file\gulpfile.js:25:4)

Hi there,

I get this error message after running gulp. relating to the loadTasks function in gulpfile.js. Didn't get any errors after running npm install (though tere were a few deprecation warnings). Running gulp v 3.9.1

Is there something wrong with my setup here? Can't see any dependency issues in the package json file

Many thanks in advance for any help!

**Comment by danmindru** [comment]
Hi there, you need at least node v5.x to compile since version 4.0.0
Can you give that I try and see if you have any problems?

FYI if you want to easily switch between node versions you can make use of [nvm](https://github.com/creationix/nvm). Otherwise just globally update :)

**Comment by Mulegoat** [comment]
Many thanks danmindru!

Been a while since I updated Node...always fills me with dread :)
