### ISSUE TITLE
cellpadding, cellspacing, align CSS properties?

### ISSUE THREAD

**Issue by HMDH** [fadeit/responsive-html-email-signature#30]
These are not valid CSS properties. Why are they used in your template's CSS?

Initially, I thought maybe postCSS is applied to transform them, but then I noticed that they are inlined as is in the HTML file.

**Comment by danmindru** [comment]
They have been once valid, but now deprecated (see https://developer.mozilla.org/en/docs/Web/HTML/Element/table). Unfortunately, a lot of email clients (big ones, i.e. Outlook) are grossly out of date, so they in fact use these attributes.

Doing a quick Google will reveal some more details.
It's just how it with email clients 💔

Some refs:
https://templates.mailchimp.com/development/html/ 
https://litmus.com/community/learning/13-foundations-email-coding-101

**Comment by HMDH** [comment]
Those are HTML attributes. Using them also as CSS properties is useless.

**Comment by danmindru** [comment]
Ah sorry, now I got the question. There's a plugin that adds those as attributes (inline-css). A lot more have been added in https://github.com/jonkemp/inline-css/pull/16.

It's really helpful when you have to add these on a bunch of *<td>s*. Makes the markup a lot cleaner.

See the code @ https://github.com/breather/inline-css/blob/760e9f59b57f7124c931fdc79aa74999ae64f882/lib/inline-css.js#L177-L188
