### ISSUE TITLE
Issues running gulp

### ISSUE THREAD

**Issue by osinho** [fadeit/responsive-html-email-signature#32]
Hi there, please provide some info about your environment before submitting this issue:
- device        : MacBook Pro (Retina, 15', Mid 2014)
- OS            : OSX El Capitan 10.11.6 (15G1217)
- email client  : 
- node version  : v4.4.0 installed in /Users/myusername/.nvm/versions/node | v7.10.0 installed in /usr/local/Cellar/node
- npm version   : 4.6.1
- error message :

MacBook-Pro:sig myusername$ gulp
/Users/myusername/Downloads/sig/tasks/build.js:98
              confItems = [...current]
                           ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at loadTasks (/Users/myusername/Downloads/sig/gulpfile.js:26:5)
    at Array.map (native)
    at Object.<anonymous> (/Users/myusername/Downloads/sig/gulpfile.js:25:4)

When running gulp the above error message comes up and (of course) no dist folder with contents is created.

I assume it has something to do with the two versions of node installed? I cannot find a way to fix this though. Any ideas? Thanks so much guys - highly appreciated.

**Comment by danmindru** [comment]
Hey @osinho, it's because of the node version indeed.
That's a ES6 spread, therefore you need a higher version of node.

I see you are using nvm, so what you can do is:

```bash
cd /path/to/responsive-html-email-signature
rm -rf node_modules
nvm install v7
nvm use v7
npm i
gulp # should work now
```

**Comment by osinho** [comment]
@danmindru, dude, you're awesome! Works like a charm now. Thanks!

**Comment by danmindru** [comment]
Glad to help @osinho! Happy coding :-)

**Comment by polaroi8d** [comment]
Helps my problem too. Thanks!
