### ISSUE TITLE
Gulp tasks finish but the process never exits. 

### ISSUE THREAD

**Issue by solancer** [fadeit/responsive-html-email-signature#33]
- device        : Mac Book Pro 2015
- OS            :  iOS
- email client  : NA
- node version  : 8.0
- npm version   :  5.0
- error message : NA

The gulp build process finishes but never gets exited

PFA below screenshot

![screen shot 2017-06-04 at 2 16 33 am](https://cloud.githubusercontent.com/assets/800668/26756971/20ed1fa2-48cc-11e7-9e6c-4c1d5849b40a.png)

**Comment by ozooner** [comment]
It states in the README:
> $ gulp # By default, HTML & CSS files in './src' will be watched for changes

In other words the process is watching for changes and if it spots one, it will re-run the build process for your convenience.

If you just want to build without watching, run `gulp build`
