### ISSUE TITLE
Create new templates

### ISSUE THREAD

**Issue by johnfcporto** [fadeit/responsive-html-email-signature#35]
Hi there, please provide some info about your enviornment before submiting this issue:
- device        : virtual box
- OS            : ubuntu 16.04
- email client  : outlook
- node version  : v8.6.0
- npm version   : v5.3.0
- error message : if i go to folder "templates" and copy the folder "fadeit" from the folder "examples". when i run gulp i got an error message. My doubt is how do I create my own template. Do I have to create a new folder in the folder "templates"?

**Comment by danmindru** [comment]
Right. Sorry for the confusion, the examples were a little bit out of date.

You can create your own template either by starting from the generic examples in `/templates` or by copy-pasting any of the templates in `/demo/examples`. I guess people usually extend those in `/templates`, so it slipped under my radar.

Should work fine now.

**Comment by reederz** [comment]
Closing.
