### ISSUE TITLE
Question: PHP Script receive val base64 decode and generate signaturet then send it by mail.

### ISSUE THREAD

**Issue by Zwordi** [fadeit/responsive-html-email-signature#38]
Hello There,

Not really an issue to discut but a small story.
I took your project in order to have signature for one of our customer generated.
Then i look on a way to have it automaticly generated and sent by email.
We are using PWM https://github.com/pwm-project/pwm for user self service management for changing password and updating information which is writting back to the AD.

Using the Update Profile Module we are able to use a "Post-Action" which let use send request to webservice or ldap based on user's detail.
I use this feature to send a post request with all the information required for generating signature to a php script.

The script is working but could be improved. The script decode the base64 string to fullfil variable, then we generate the conf.json then we ran gulp using shellexec.
I added phpmailer in order to send the zip which contains the signatures to Office365 user mailbox.
Do you think this script could be an addition to your project or should I push it on his own project ?

Please let me know.

**Comment by danmindru** [comment]
Hi @Zwordi, that sounds pretty cool.
I think it is a bit beyond the scope of this project. However, if you'd make another repository for your script, we could add a section in the README here and link to it. Sounds good?

Dan

**Comment by danmindru** [comment]
(Note: related to #27. Making the a more cli-friendly version of the script could be helpful for these cases.)

**Comment by Zwordi** [comment]
Hi, Sorry for the delay.

I will keep you in touch about the repo.

Zwordi
