### ISSUE TITLE
I get an error on npm install. May I get some help?

### ISSUE THREAD

**Issue by johannesgriesshammer** [fadeit/responsive-html-email-signature#41]
Hi there, please provide some info about your environment before submitting this issue:
- device        : 
- OS            : Windows 10 64 Bit | macOS Sierra Version 10.12.6
- email client  : none
- node version  : v8.9.0
- npm version   :  5.5.1
- error message :
on npm install:

npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t git://github.com/cheeriojs/cheerio.git
npm ERR!
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.112]: errno=Connection refused
npm ERR! github.com[1: 192.30.253.113]: errno=Connection refused
npm ERR!
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac_15/.npm/_logs/2017-11-17T11_11_01_103Z-debug.log

**Comment by danmindru** [comment]
Hi, it look like some sort of firewall issue to me. Either that, or github was down for a bit. Did you try installing on a different network?

**Comment by johannesgriesshammer** [comment]
It really seems to be a Firewall issue. Cheerio was the only package I had difficulties to download. My work network didn't allow it. At home, it's functioning without problems.

Thanks for your input, man.

**Comment by danmindru** [comment]
Great that you got it to work :)
