### ISSUE TITLE
How to get this to work?

### ISSUE THREAD

**Issue by McYoda** [fadeit/responsive-html-email-signature#42]
Hi guys
Downloaded this project since I urgenty need to create multiplatform responsive signatures.
But sorry, I'm no Java developer. Don't have any idea how to run this "gulp thingy" at all.
Any hints for a newbie would be extremely welcome.
Thanks and cheers
Martin

**Comment by danmindru** [comment]
Hi there,
The first steps are to [install node.js](https://nodejs.org/en/download/), clone the repository, open a command line window in it and run ‘npm install’ to grab all dependencies.
At this point you should install gulp cli globally by running ‘npm install -g gulp-cli’.
Afterwards you should be able to run gulp (also through the command line) which builds the signatures into the ./dist directory.


More information on how to edit the signatures you can find in the project README, it doesn’t require JavaScript knowledge per say, but you do have to update values in a configuration file.

Hope this helps.
