### ISSUE TITLE
Images not working

### ISSUE THREAD

**Issue by haizanboerg** [fadeit/responsive-html-email-signature#43]
Hi there, please provide some info about your enviornment before submiting this issue:
- device        : 
- OS            : Debian 8.9
- email client  : none
- node version  : 7.4.0
- npm version   : 4.0.5
- error message : none

Images got not converted into base64 ore used otherwise, signature in /dist gives error "file not found" in browser.

I have changed nothing just installed and used gulp to generate files from templates, fadeit images wont be load and signature in /dist showing this:

img src="/assets/light.png" alt="light logo" class="footer__main__col2__td__img" style="border: 0; height: auto; max-height: 38px; max-width: 100%; padding-left: 10px; padding-top: 6px;"

Has this something to doe with the renaming of .src ? because i used this tool often times and since then its images wont embedded as base64.

For Help i would be very grateful

**Comment by danmindru** [comment]
Hey, thanks for the heads up. Swapped the plugin for something else and it seems to work. 
Would you clone the bugfix branch and give it a try?

https://github.com/fadeit/responsive-html-email-signature/tree/bugfix/base64-inline

**Comment by haizanboerg** [comment]
Done...
Works like charm... thx.

Best Regards
