### ISSUE TITLE
How to add the signature in Outlook 365

### ISSUE THREAD

**Issue by davisgarcesn** [fadeit/responsive-html-email-signature#45]
Hi there, please provide some info about your enviornment before submiting this issue:
- device        : Asus
- OS            : Windows 10
- email client  : Office 365

Hi! I saw this and I think is really good. I have 2 questions.

1: how can I modify the template and add my own template? It is just only add the template as html file?
2: how can I install the signature in Outlook 365?

**Comment by danmindru** [comment]
Hi there,

1. Sure you can modify templates or even add your own. Take a look in the templates directory for a couple examples: [/templates](https://github.com/fadeit/responsive-html-email-signature/tree/master/templates). 

2. I don't have an Outlook 365 account myself, but it seems rather straight forward to add an email signature: https://www.mail-signatures.com/articles/how-to-set-up-or-change-email-signature-in-outlook-on-the-web-office-365-and-exchange-2016/

Good luck!

**Comment by devcondesign** [comment]
Youtube have plenty of tutorials about how to install html signatures.
Maybe this one is the solution. https://youtu.be/0pEQmCKL8Ak
