### ISSUE TITLE
outlook 2010 issues

### ISSUE THREAD

**Issue by dusskapark** [fadeit/responsive-html-email-signature#7]
Hi, 

Thanks for providing this wonderful email signature templates and gulp tasks. I love it :)
BTW, I can import htmls files on my OSX mail app but I cound't find a way for OUTLOOK 2010 platform. 
Is it impossible to use HTML file as a signature on OUTLOOK platform?

**Comment by danmindru** [comment]
Hi there, I'm glad you found it helpful!
Not an Outlook user myself, but I think the process is similar to the Apple Mail tutorial. Try to go to your outlook preferences, add a signature and then look for the path where Outlook stores signatures. Figure out which one you just added and open it up with a text editor and paste the HTML code in (or open all of them and identify it by its content).
Not completely if it'll work, but it's my best guess. Alternatively you could follow [this article](http://www.knowthenetwork.com/2012/05/how-to-add-an-html-email-signature-to-outlook-2010/), but I am affraid some CSS bits might be ommited that way.

If you get it working it would be great if you added the steps to the README and made a pull request. I'll be happy to merge it in, maybe it will help others :-)

**Comment by dusskapark** [comment]
### Outlook 2010 Client for Windows

Unfortnately, Outlook 2010 client dosen't support HTML file import features for your email template. But you can add your own signatures by simple Copy and paste like **Solution 2** above. 

![2016-04-17 6 57 36](https://cloud.githubusercontent.com/assets/4177529/14586344/15585e40-04d0-11e6-8cb4-3b72aa8c30d1.png)
![2016-04-17 6 58 15](https://cloud.githubusercontent.com/assets/4177529/14586345/155b3e58-04d0-11e6-8a11-7e7e6e1094d8.png)

- Open built html file on `/dist` folder and Ctrl A + C 
- Open Outlook 2010 and go to `File > Option > Mail > Signature` 
- Create new signature and paste copyed one

> **NB**: base 64 will not be shown on Outlook 2010 client. So, I recommend to use external url if you want to use images.

**Comment by johnfcporto** [comment]
Im having some trouble to get my signatures to work on outlook.. i ve tried the 2 solutions but the images are not loaded and the structure of the signature differs from the original. Anyone has some suggestions to make it work?
